# -*- coding: utf-8 -*-
"""COMVis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yOONmJ2F0vy0Pg4G2YlpK0HGMHO9fPU
"""

# Commented out IPython magic to ensure Python compatibility.
##NIZHAM FARIS HASBILLAH


# 1. IMPOR LIBRARY

import os
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import kagglehub



from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree



warnings.filterwarnings('ignore')

# Configure matplotlib for better display in Colab
# %matplotlib inline
plt.rcParams['figure.dpi'] = 100

# 2. DOWNLOAD AND LOAD DATASET

print("=" * 70)
print("DOWNLOADING DATASET")
print("=" * 70)

path = kagglehub.dataset_download("mubeenshehzadi/salary-dataset")
print(f"Path to dataset files: {path}\n")

# List files in directory
files_in_directory = os.listdir(path)
print(f"Files found: {files_in_directory}")

# Load CSV file
csv_files = [f for f in files_in_directory if f.endswith('.csv')]
if csv_files:
    csv_file_name = csv_files[0]
    full_csv_path = os.path.join(path, csv_file_name)
    df = pd.read_csv(full_csv_path)
    print(f"Successfully loaded '{csv_file_name}'\n")
else:
    raise FileNotFoundError("No CSV files found in the dataset directory")

# 3. EKSPLORASI DATA

print("=" * 70)
print("EKSPLORASI DATA")
print("=" * 70)



print("\nBentuk Dataset:", df.shape)
print("\n5 Baris Pertama:")
print(df.head())
print("\nTipe Data:")
print(df.dtypes)
print("\nNilai yang Hilang:")
print(df.isnull().sum())

# 4. PEMBERSIHAN DATA

print("\n" + "=" * 70)
print("PEMBERSIHAN DATA")
print("=" * 70)



# Hapus nilai yang hilang
initial_rows = len(df)
df.dropna(inplace=True)
print(f"Menghapus {initial_rows - len(df)} baris dengan nilai yang hilang")



# Standarisasi tingkat pendidikan
df["Education Level"].replace("Phd", 'PhD', inplace=True)
print("Standarisasi nilai 'Education Level'")



print(f"\nBentuk dataset akhir: {df.shape}")

# 5. ANALISIS DATA EKSPLORATIF (EDA)

print("\n" + "=" * 70)
print("ANALISIS DATA EKSPLORATIF")
print("=" * 70)



# Atur gaya plot
sns.set(rc={'figure.figsize': (15, 8)})
sns.set_style("darkgrid")



# Distribusi gender
plt.figure(figsize=(10, 6))
sns.countplot(x=df["Gender"])
plt.title("Distribusi Gender")
plt.show()



# Distribusi tingkat pendidikan
plt.figure(figsize=(10, 6))
sns.countplot(x=df["Education Level"])
plt.title("Distribusi Tingkat Pendidikan")
plt.show()



# Distribusi gaji
plt.figure(figsize=(10, 6))
sns.histplot(df['Salary'], bins=50, kde=True)
plt.title('Distribusi Gaji')
plt.xlabel('Gaji')
plt.ylabel('Frekuensi')
plt.show()



# Usia vs Gaji
plt.figure(figsize=(15, 8))
sns.lineplot(x=df["Age"], y=df["Salary"])
plt.title("Usia vs Gaji")
plt.xlabel("Usia")
plt.ylabel("Gaji")
plt.show()



# Pengalaman vs Gaji
plt.figure(figsize=(15, 8))
sns.lineplot(x=df["Years of Experience"], y=df["Salary"])
plt.title("Tahun Pengalaman vs Gaji")
plt.xlabel("Tahun Pengalaman")
plt.ylabel("Gaji")
plt.show()

# 6. REKAYASA FITUR

print("\n" + "=" * 70)
print("REKAYASA FITUR")
print("=" * 70)



# Pisahkan fitur dan target
X = df.drop("Salary", axis=1)
y = df["Salary"]



# Identifikasi kolom numerik dan kategorikal
numerical_cols = []
categorical_cols = []



for col in X.columns:
    if X[col].dtype == 'object' or pd.api.types.is_categorical_dtype(X[col]):
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)



print(f"Kolom numerik: {numerical_cols}")
print(f"Kolom kategorikal: {categorical_cols}")

# 7. PEMBAGIAN DATA LATIH-UJI

print("\n" + "=" * 70)
print("PEMBAGIAN DATA LATIH-UJI")
print("=" * 70)



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Ukuran data latih: {X_train.shape[0]}")
print(f"Ukuran data uji: {X_test.shape[0]}")

# 8. MEMBANGUN PIPELINE MACHINE LEARNING

print("\n" + "=" * 70)
print("MEMBANGUN PIPELINE ML")
print("=" * 70)



# Buat transformer
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])



categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])



# Buat preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)



# Buat pipeline lengkap
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])



print("Pipeline berhasil dibuat")
print("\nLangkah-langkah Pipeline:")
for idx, (name, step) in enumerate(pipeline.steps, 1):
    print(f"  {idx}. {name}: {type(step).__name__}")

# 9. LATIH MODEL

print("\n" + "=" * 70)
print("MELATIH MODEL")
print("=" * 70)



pipeline.fit(X_train, y_train)
print("Pelatihan model berhasil diselesaikan")

# 10. MEMBUAT PREDIKSI
print("\n" + "=" * 70)
print("MEMBUAT PREDIKSI")
print("=" * 70)



y_predict = pipeline.predict(X_test)
print(f"Prediksi dihasilkan untuk {len(y_predict)} sampel")

# 11. EVALUASI MODEL

print("\n" + "=" * 70)
print("EVALUASI MODEL")
print("=" * 70)



mse = mean_squared_error(y_test, y_predict)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_predict)



print(f"Mean Squared Error (MSE): {mse:,.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:,.2f}")
print(f"Skor R-squared (R²): {r2:.4f}")



# Interpretasi
print("\nPerforma Model:")
print(f"  - Model menjelaskan {r2*100:.2f}% varians dalam gaji")
print(f"  - Rata-rata kesalahan prediksi: ${rmse:,.2f}")

# 12. VISUALISASI HASIL

print("\n" + "=" * 70)
print("MEMVISUALISASIKAN HASIL")
print("=" * 70)



# Aktual vs Prediksi (plot KDE)
plt.figure(figsize=(15, 8))
sns.kdeplot(y_test, color="red", label="Aktual", fill=True)
sns.kdeplot(y_predict, color="green", label="Prediksi", fill=True)
plt.title("Distribusi Gaji Aktual vs Prediksi")
plt.xlabel("Gaji")
plt.ylabel("Densitas")
plt.legend()
plt.show()



# Aktual vs Prediksi (plot Regresi)
plt.figure(figsize=(15, 8))
sns.regplot(x=y_test, y=y_predict, color="red", scatter_kws={'alpha': 0.5})
plt.title("Gaji Aktual vs Prediksi (Plot Regresi)")
plt.xlabel("Gaji Aktual")
plt.ylabel("Gaji Prediksi")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         'k--', lw=2, label='Prediksi Sempurna')
plt.legend()
plt.show()

# 13. VISUALIZE DECISION TREE

print("\n" + "=" * 70)
print("MEMVISUALISASIKAN POHON KEPUTUSAN")
print("=" * 70)

# Ambil satu pohon dari random forest
tree_estimator = pipeline.named_steps['regressor'].estimators_[0]

# Dapatkan nama fitur
onehot_encoder = pipeline.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot']
categorical_feature_names = onehot_encoder.get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(categorical_feature_names)

# Plot pohon
plt.figure(figsize=(20, 10))
plot_tree(
    tree_estimator,
    filled=True,
    feature_names=all_feature_names,
    rounded=True,
    precision=1
)
plt.title("Contoh Pohon Keputusan dari Model Random Forest")
plt.show()

print("\n" + "=" * 70)
print("ANALISIS SELESAI")
print("=" * 70)